<?php

namespace Tests\Unit\Repositories;

use App\Helpers\GetUsersHelper;
use App\Repositories\UserRepo;
use App\User;
use Faker\Factory;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use PHPUnit\Framework\TestCase;


class UserRepoTest extends TestCase
{
    protected $user;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Factory::create();
        $user_type = GetUsersHelper::getStaff([ 'super_admin', 'librarian' ])[rand(0, 2)];
        $this->user = [
            'name' => $this->faker->name,
            'email' => $this->faker->safeEmail,
            'username' => $this->faker->userName,
            'password' => Hash::make($user_type),
            'user_type' => $user_type,
            'code' => strtoupper(Str::random(10)),
            'remember_token' => Str::random(10),
        ];
        $this->userRepo = new UserRepo();

    }

    public function create()
    {
        $user = $this->userRepo->create($this->user);
        $this->assertInstanceOf(User::class, $user);


    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_example()
    {
        $this->assertTrue(true);
    }
}
